POST http://localhost:8042/v1/api
Accept: */*
Cache-Control: no-cache

{"jsonrpc":"2.0","method":"get-wallet-node","params":{"public-key": "AbufXXhRwFJuvkjCiBsBh8FJkJTB8nH2bZn6QZheX74k8TgDf"},"id":"1"}

###