POST http://localhost:8042/v1/api
Accept: */*
Cache-Control: no-cache

{"jsonrpc":"2.0","method":"get-transaction","params":{"digest": "Kc7jNGoJuvC85BoCK2dASu5cUQ1wgzc2JFt8iBijbfcvbqKEb"},"id":"1"}

###
